### ISSUE TITLE
在华为honor 8 lite上注册jni方法异常了

### ISSUE THREAD

**Issue by achenglike** [ysrc/Anti-Emulator#2]
art: Failed to register native method com.qtfreet.anticheckemulator.emulator.JniAnti.getApkSign()Ljava/lang/String; in /data/app/cn.com.x x x-1/base.apk
07-11 17:28:28.329 12997-12997/? E/art: ----- class 'Lcom/qtfreet/anticheckemulator/emulator/JniAnti;' cl=0x12c59550 -----
07-11 17:28:28.329 12997-12997/? E/art:   objectSize=432 (432 from super)
07-11 17:28:28.329 12997-12997/? E/art:   access=0x0008.0001
07-11 17:28:28.329 12997-12997/? E/art:   super='java.lang.Class<java.lang.Object>' (cl=0x0)
07-11 17:28:28.329 12997-12997/? E/art:   vtable (0 entries, 11 in super):
07-11 17:28:28.329 12997-12997/? E/art:   direct methods (4 entries):
07-11 17:28:28.329 12997-12997/? E/art:      0: void com.qtfreet.anticheckemulator.emulator.JniAnti.<clinit>()
07-11 17:28:28.329 12997-12997/? E/art:      1: int com.qtfreet.anticheckemulator.emulator.JniAnti.checkAntiFile()
07-11 17:28:28.329 12997-12997/? E/art:      2: java.lang.String com.qtfreet.anticheckemulator.emulator.JniAnti.getCpuinfo()
07-11 17:28:28.329 12997-12997/? E/art:      3: java.lang.String com.qtfreet.anticheckemulator.emulator.JniAnti.getKernelVersion()

---------------------------------
c 方法getCpuInfo出现了未return的时候

`char *getCpuInfo() {
   
    return (char *) "NULLLLLLLLL";  //# 需要最终有返回，否则异常。
}

`

**Comment by Qrilee** [comment]
方便把/proc/cpuinfo文件上传一下么

**Comment by achenglike** [comment]
Processor	: AArch64 Processor rev 4 (aarch64)
processor	: 0
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 4
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 5
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 6
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 7
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

**Comment by achenglike** [comment]
上面包的错误跟我后面提到的这个问题没有关系，分别是两个问题，应该是混淆导致的，我加入防止混淆就正常了：
-keep class com.qtfreet.anticheckemulator.** { *; }

**Comment by Qrilee** [comment]
部分国产机型对机型做了比较大的改造，本身cpuinfo这个文件是会包含Hardware字段的，或者是modle info ，部分华为机型就没有这些字段
