### ISSUE TITLE
Native method not found: com.hotgirlsapp.emulator.JniAnti.getCpuinfo:()Ljava/lang/String

### ISSUE THREAD

**Issue by nangongyanya** [ysrc/Anti-Emulator#3]
在ADT Bundle上执行时提示这个错误，所有的JNI方法都出现找不到的异常。

**Comment by Qrilee** [comment]
这个无法判断是哪里问题，建议帖上代码

**Comment by sickworm** [comment]
最大可能是没 System.loadLibrary，或者 so 没有编译出来（so不存在不会崩溃）

**Comment by Qrilee** [comment]
@SickWorm 根据他的类名应该是改了java类名但并没有修改jni路径导致的无法找到方法
