### ISSUE TITLE
8.0系统 getVersionInfo失败

### ISSUE THREAD

**Issue by achenglike** [ysrc/Anti-Emulator#4]
8.0系统中native-lib.cpp#getVersionInfo()无法读取到设备版本，由于手头没有设备，目前怀疑/proc/version文件可能有变动

**Comment by Qrilee** [comment]
是的 ，8.0以上无权限访问此文件，可以使用jni函数uname重新取值

**Comment by achenglike** [comment]
不好意思，对jni不是十分了解，“可以使用jni函数uname重新取值”这句话不是很明白需要如何处理

**Comment by achenglike** [comment]
是指命令行命令 uname  吧，然后从jni中去调用这个命令
